### ISSUE TITLE
Feature Request: Natively Support MagicLink in React Native v5 SDK

### ISSUE THREAD

**Issue by brien-crean** [thirdweb-dev/js#4701]
While attempting to upgrade our project to 0.74.5 we get a Gradle build error due to an older version of `expo-application` (5.8.3) which is installed as a dependency of `@thirdweb-dev/react-native`.

Is there a plan to update `expo-application` along with other outdated expo dependencies to support react native 0.74 and 0.75?

yarn.lock segment
```
"@thirdweb-dev/react-native@npm:latest":
  version: 0.8.0
  resolution: "@thirdweb-dev/react-native@npm:0.8.0"
  dependencies:
    "@aws-sdk/client-lambda": 3.549.0
    "@aws-sdk/credential-providers": 3.549.0
    "@coinbase/wallet-mobile-sdk": 1.0.13
    "@paperxyz/embedded-wallet-service-sdk": ^1.2.5
    "@shopify/restyle": ^2.4.2
    "@tanstack/react-query": ^4.36.1
    "@thirdweb-dev/chains": 0.1.106
    "@thirdweb-dev/react-core": 4.6.16
    "@thirdweb-dev/sdk": 4.0.77
    "@thirdweb-dev/storage": 2.0.14
    "@thirdweb-dev/wallets": 2.5.17
    abitype: 1.0.0
    amazon-cognito-identity-js: ^6.3.12
    aws-amplify: ^5.3.18
    expo-application: 5.8.3
    expo-clipboard: ^4.8.0
    expo-document-picker: ^11.10.1
    expo-file-system: ^16.0.8
    expo-secure-store: ^12.8.1
    react-native-aes-gcm-crypto: ^0.2.2
    react-native-camera: ^4.2.1
    react-native-inappbrowser-reborn: ^3.7.0
    react-native-modal: ^13.0.1
    react-native-quick-base64: ^2.1.0
    react-native-quick-crypto: ^0.6.1
    secrets.js-34r7h: ^2.0.2
    tiny-invariant: ^1.3.3
  peerDependencies:
    ethers: ">=5.5.1 <6"
    expo: ">=47"
    react: ">=18.0.0"
    react-native: ">=0.71.0"
    react-native-mmkv: ">=2.11.0"
    react-native-qrcode-svg: ">=6.3.0"
    react-native-svg: ">=15.1.0"
  dependenciesMeta:
    amazon-cognito-identity-js:
      optional: true
    react-native-aes-gcm-crypto:
      optional: true
    react-native-camera:
      optional: true
    react-native-inappbrowser-reborn:
      optional: true
    react-native-quick-base64:
      optional: true
    react-native-quick-crypto:
      optional: true
  checksum: 9f7002eeae4acf16f81b07e9b32102d861d88805287d1a931c292e8b1022486848b739134c74d9575508d935620e81b9330ff8465055032caa6b78bbc947480b
  languageName: node
  linkType: hard
  ```
